#!/usr/bin/env python3
"""yubikey-age-enrollment-drill.py — regalia#17 acceptance criterion 4 on real YubiKeys.

Multi-enrollment (ADR-0002 D5): every YubiKey-held role is enrolled on at least two tokens, each
with its OWN on-device key, plus a break-glass recipient; losing one token loses nothing. This
drill proves that on hardware, for a SOPS consumer:

  1  a SOPS file is encrypted to token A, token B and the break-glass recipient;
     each of the three decrypts it on its own
  2  token A is withdrawn: its recipient is removed (`sops updatekeys`) and the data key rotated
     (`sops rotate`); B and break-glass still decrypt, and A's identity is REFUSED
     (negative control: without it, "withdrawn" is a claim)
  3  a replacement key is generated ON a token and enrolled; the replacement, B and break-glass
     decrypt, A is still refused
  and after EVERY step the plaintext is byte-identical to the original: nothing becomes
  undecryptable at any step.

PINs come from the environment (YK_PIN_<serial>) and are typed into the plugin's prompt over a
pty; they never reach argv, the transcript or the work directory. The age identity stubs hold no
key material (the private key is on the card). The break-glass identity IS a key: it is generated
per run in the work directory and deleted at the end.

  YK_PIN_36345471=… YK_PIN_36344616=… yubikey-age-enrollment-drill.py \\
      --workdir /build/k17 --token A=36345471:20 --token B=36344616:20 --replacement A2=36345471:19

Each --token SERIAL:SLOT must already hold an age-plugin-yubikey key (identity stub in
<workdir>/<NAME>.id); the replacement is generated by the drill (slot must be empty). Requires
sops, age-plugin-yubikey, age-keygen and ykman on PATH; Python standard library only.
"""
import argparse
import hashlib
import os
import pty
import re
import select
import shutil
import subprocess
import sys
import termios
import time

PROMPT = r"Enter PIN for YubiKey with serial (\d+)(?=\D)"  # the lookahead: never a serial cut by a read boundary


def log(lines, text):
    stamp = time.strftime("%H:%M:%S", time.gmtime())
    for line in text.splitlines() or [""]:
        entry = f"{stamp} {line}"
        print(entry, flush=True)
        lines.append(entry)


def pin_for(serial):
    value = os.environ.get(f"YK_PIN_{serial}")
    if not value:
        sys.exit(f"YK_PIN_{serial} is not set")
    return value


def run_pty(argv, env, timeout=120):
    """Run argv on a pty, typing the PIN into each age-plugin-yubikey prompt. Returns
    (exit status, output with PINs redacted). A pty, because the plugin reads the PIN from the
    terminal and a PIN must not go on argv. Standard library only: the ceremony's Python is
    hash-pinned, and this adds nothing to it."""
    pid, fd = pty.fork()
    if pid == 0:
        try:
            os.execvpe(argv[0], argv, env)
        finally:
            os._exit(127)
    buffer, answered, deadline = "", 0, time.monotonic() + timeout
    while True:
        remaining = deadline - time.monotonic()
        if remaining <= 0:
            os.kill(pid, 9)
            break
        ready, _, _ = select.select([fd], [], [], remaining)
        if not ready:
            continue
        try:
            chunk = os.read(fd, 4096)
        except OSError:  # EIO: the child closed the pty
            break
        if not chunk:
            break
        buffer += chunk.decode("utf-8", "replace")
        prompts = list(re.finditer(PROMPT, buffer))
        while answered < len(prompts):
            # Type only once the prompt has turned echo off: input typed earlier can be flushed by
            # the prompt, and would be echoed into this buffer (ykman hangs on exactly that).
            until = time.monotonic() + 5
            while termios.tcgetattr(fd)[3] & termios.ECHO and time.monotonic() < until:
                time.sleep(0.02)
            os.write(fd, (pin_for(prompts[answered].group(1)) + "\n").encode())
            answered += 1
    _, status = os.waitpid(pid, 0)
    os.close(fd)
    for key, value in os.environ.items():
        if key.startswith("YK_PIN_") and value:
            buffer = buffer.replace(value, "<redacted>")
    return os.waitstatus_to_exitcode(status), buffer


def recipient_of(stub_path):
    text = open(stub_path).read()
    match = re.search(r"Recipient: (age1yubikey1[0-9a-z]+)", text)
    if not match:
        sys.exit(f"{stub_path}: no recipient line")
    return match.group(1)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--workdir", required=True)
    ap.add_argument("--token", action="append", required=True, help="NAME=SERIAL:SLOT (exactly two)")
    ap.add_argument("--replacement", required=True, help="NAME=SERIAL:SLOT, generated by the drill")
    ap.add_argument("--withdraw", default=None, help="NAME of the token to withdraw (default: the first)")
    args = ap.parse_args()

    for tool in ("sops", "age-plugin-yubikey", "age-keygen", "ykman"):
        if not shutil.which(tool):
            sys.exit(f"{tool} is required on PATH")
    work = os.path.abspath(args.workdir)
    os.chdir(work)
    # Only the SOPS_AGE_KEY_FILE set per call may supply an identity. sops also loads SOPS_AGE_KEY(_CMD),
    # SSH keys and <config>/sops/age/keys.txt, and an operator's own YubiKey stub there would make
    # a "decrypts on its own" row pass on the wrong key and a refusal row fail. An inherited
    # SOPS_AGE_RECIPIENTS would change what `sops -e` encrypts to.
    env = {k: v for k, v in os.environ.items() if not k.startswith("SOPS_")}
    isolated_home = os.path.join(work, "empty-home")
    os.makedirs(isolated_home, exist_ok=True)
    env.update(HOME=isolated_home, XDG_CONFIG_HOME=os.path.join(isolated_home, ".config"))
    transcript = []

    def parse(spec):
        name, _, rest = spec.partition("=")
        serial, _, slot = rest.partition(":")
        # The name becomes a file name in the work directory: no path, and never the break-glass key's.
        if not (re.fullmatch(r"[A-Za-z0-9_-]+", name) and name not in ("bg", "break-glass")
                and serial.isdigit() and slot.isdigit()):
            sys.exit(f"bad token spec {spec!r}; want NAME=SERIAL:SLOT")
        return name, serial, slot

    tokens = [parse(t) for t in args.token]
    if len(tokens) != 2 or tokens[0][1] == tokens[1][1]:
        sys.exit("exactly two --token entries on two distinct serials")
    withdrawn = args.withdraw or tokens[0][0]
    kept = [t for t in tokens if t[0] != withdrawn]
    if len(kept) != 1:
        sys.exit(f"--withdraw {withdrawn!r} does not name one of the tokens")
    repl_name, repl_serial, repl_slot = parse(args.replacement)
    # A replacement that reuses a token's name or slot would overwrite that token's stub or key, and
    # the rows after it would test the wrong key while reporting PASS.
    if repl_name in {t[0] for t in tokens} or (repl_serial, repl_slot) in {(t[1], t[2]) for t in tokens}:
        sys.exit("--replacement must use a new NAME and a slot no --token uses")

    identities = {}
    for name, serial, slot in tokens:
        stub = f"{name}.id"
        if not os.path.exists(stub):
            sys.exit(f"{stub} missing: generate {name} on {serial} slot {slot} first")
        identities[name] = (stub, recipient_of(stub))
        log(transcript, f"token {name}: YubiKey {serial}, retired slot {slot}, recipient {identities[name][1]}")

    # The break-glass recipient: in production the Shamir-backed software key; here a per-run one.
    subprocess.run(["age-keygen", "-o", "bg.id"], check=True, capture_output=True)
    os.chmod("bg.id", 0o600)
    bg_recipient = subprocess.run(["age-keygen", "-y", "bg.id"], check=True, capture_output=True, text=True).stdout.strip()
    identities["break-glass"] = ("bg.id", bg_recipient)
    log(transcript, f"break-glass: software age key generated for this run, recipient {bg_recipient}")

    def set_rule(names):
        recipients = ",".join(identities[n][1] for n in names)
        with open(".sops.yaml", "w") as f:
            f.write(f'creation_rules:\n  - path_regex: secret\\.yaml$\n    age: "{recipients}"\n')
        log(transcript, f"  .sops.yaml recipients: {', '.join(names)}")

    def decrypts(name):
        stub = identities[name][0]
        if os.path.exists("out.yaml"):
            os.remove("out.yaml")
        status, output = run_pty(["sops", "-d", "--output", "out.yaml", "secret.yaml"],
                                 dict(env, SOPS_AGE_KEY_FILE=os.path.join(work, stub)))
        if status != 0 or not os.path.exists("out.yaml"):
            # A refusal counts only when SOPS says no key it holds matched. A card that is absent, a
            # wrong PIN or a plugin crash is also a non-zero exit, and would make the negative
            # control pass for the wrong reason.
            # sops wraps each key's error over "| "-prefixed lines, and ends every failure, whatever
            # its cause, with the same generic trailer. So unwrap, split per master key, and count a
            # refusal only when EVERY key that failed says the identity did not match it.
            # On a terminal (this pty) sops also colours "FAILED" with ANSI codes: strip them first.
            plain = re.sub(r"\x1b\[[0-9;]*m", "", output.replace("\r", ""))
            flat = re.sub(r"\n\s*\|\s*", " ", plain)
            blocks = re.split(r"\n\s*age1[0-9a-z]+: FAILED", flat)[1:]
            if blocks and all("did not match any of the recipients" in b and "failed to load age identities" not in b
                              for b in blocks):
                return False, f"identity did not match any of the {len(blocks)} recipients"
            return False, "UNEXPECTED ERROR: " + " | ".join(l.strip() for l in flat.splitlines() if l.strip())[-300:]
        with open("out.yaml", "rb") as f:
            same = hashlib.sha256(f.read()).hexdigest() == plain_sha
        os.remove("out.yaml")
        return same, "byte-identical" if same else "DIFFERENT PLAINTEXT"

    failures = []

    def expect(name, should):
        ok, detail = decrypts(name)
        verdict = "PASS" if ok == should and not detail.startswith("UNEXPECTED") else "FAIL"
        if verdict == "FAIL":
            failures.append(f"{name} {'decrypt' if should else 'refusal'}")
        log(transcript, f"  [{verdict}] {name}: {'decrypts' if ok else 'refused'} ({detail})")

    def manage(args_, as_name):
        status, output = run_pty(["sops"] + args_, dict(env, SOPS_AGE_KEY_FILE=os.path.join(work, identities[as_name][0])))
        if status != 0:
            log(transcript, output)
            sys.exit(f"sops {' '.join(args_)} failed (exit {status})")

    # Any exit — a sops failure, a failed generation, a missing PIN — still deletes the break-glass key
    # and keeps the record of how far the drill got.
    def write_transcript():
        with open("transcript.log", "w") as f:
            f.write("\n".join(transcript) + "\n")

    try:
        # ---- STEP 1 ---------------------------------------------------------------------------------
        log(transcript, "STEP 1 — encrypt to both tokens and break-glass; each decrypts alone")
        secret = f"drill_secret: {os.urandom(24).hex()}\n"
        plain_sha = hashlib.sha256(secret.encode()).hexdigest()
        with open("secret.yaml", "w") as f:
            f.write(secret)
        set_rule([t[0] for t in tokens] + ["break-glass"])
        subprocess.run(["sops", "-e", "-i", "secret.yaml"], check=True, env=env)
        log(transcript, f"  plaintext sha256 {plain_sha[:16]}…; {open('secret.yaml').read().count('recipient: age1')} age stanzas")
        for name in [t[0] for t in tokens] + ["break-glass"]:
            expect(name, True)

        # ---- STEP 2 ---------------------------------------------------------------------------------
        log(transcript, f"STEP 2 — withdraw {withdrawn}: remove its recipient, rotate the data key")
        set_rule([kept[0][0], "break-glass"])
        manage(["updatekeys", "-y", "secret.yaml"], kept[0][0])
        manage(["rotate", "-i", "secret.yaml"], kept[0][0])
        log(transcript, f"  {open('secret.yaml').read().count('recipient: age1')} age stanzas after updatekeys + rotate")
        expect(kept[0][0], True)
        expect("break-glass", True)
        expect(withdrawn, False)

        # ---- STEP 3 ---------------------------------------------------------------------------------
        log(transcript, f"STEP 3 — generate {repl_name} ON YubiKey {repl_serial} slot {repl_slot}, enroll it")
        status, output = run_pty(["age-plugin-yubikey", "--generate", "--serial", repl_serial, "--slot", repl_slot,
                                  "--pin-policy", "once", "--touch-policy", "never", "--name", f"regalia-k17-{repl_name}"], env)
        if status != 0:
            log(transcript, output)
            sys.exit("replacement generation failed")
        with open(f"{repl_name}.id", "w") as f:
            f.write("\n".join(l for l in output.replace("\r", "").splitlines() if l.startswith("#") or l.startswith("AGE-PLUGIN-YUBIKEY-")) + "\n")
        identities[repl_name] = (f"{repl_name}.id", recipient_of(f"{repl_name}.id"))
        log(transcript, f"  {repl_name}: recipient {identities[repl_name][1]} (a new on-device key)")
        set_rule([kept[0][0], repl_name, "break-glass"])
        manage(["updatekeys", "-y", "secret.yaml"], kept[0][0])
        expect(repl_name, True)
        expect(kept[0][0], True)
        expect("break-glass", True)
        expect(withdrawn, False)

    finally:
        if os.path.exists("bg.id"):
            os.remove("bg.id")
            log(transcript, "break-glass identity deleted")
        write_transcript()
    if failures:
        log(transcript, "DRILL FAILED: " + "; ".join(failures))
    else:
        log(transcript, "DRILL PASSED: enrolled on two tokens + break-glass → one withdrawn and refused → "
                        "replacement generated on-device and enrolled; every current recipient decrypted at every step")
    write_transcript()
    sys.exit(1 if failures else 0)


if __name__ == "__main__":
    main()
